web/router.ex
defmodule Blog.Router do
  use Blog.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Blog.Auth, repo: Blog.Repo
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", Blog do
    pipe_through :browser # Use the default browser stack


    resources "/sessions", SessionController, only: [:new, :create, :delete]
    resources "/posts", PostController, only: [:index, :show]
    get "/", PostController, :index

    scope "admin", Admin, as: :admin do
      pipe_through :authenticate_user
      resources "/posts", PostController
      resources "/users", UserController
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", Blog do
  #   pipe_through :api
  # end
end

lib/blog/endpoint.ex
defmodule Blog.Endpoint do
  use Phoenix.Endpoint, otp_app: :blog

  socket "/socket", Blog.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :blog, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  plug Plug.Session,
    store: :cookie,
    key: "_blog_key",
    signing_salt: "AFWL3Qqx"

  plug Blog.Router
end

lib/blog/repo.ex
defmodule Blog.Repo do
  use Ecto.Repo, otp_app: :blog
  use Scrivener, page_size: 10
end

web/models/admin/post.ex
defmodule Blog.Admin.Post do
  use Blog.Web, :model

  schema "posts" do
    field :title, :string
    field :content, :string

    timestamps
  end

  @required_fields ~w(title content)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/models/post.ex
defmodule Blog.Post do
  @moduledoc """
    Post represent each article of the blog
  """
  use Blog.Web, :model

  schema "posts" do
    field :title, :string
    field :content, :string

    timestamps
  end

  @required_fields ~w(title content)
  @optional_fields ~w()

  @doc """
  Creates a changeset based on the `model` and `params`.

  If no params are provided, an invalid changeset is returned
  with no validation performed.
  """
  def changeset(model, params \\ :empty) do
    model
    |> cast(params, @required_fields, @optional_fields)
  end
end

web/models/user.ex
defmodule Blog.User do
  @moduledoc """
    User is the admin of the blog.
  """

  use Blog.Web, :model

  schema "users" do
    field :email, :string
    field :password, :string, virtual: true
    field :password_hash, :string

    timestamps
  end

  def changeset(model, params \\ :empty) do
    model
    |> cast(params, ~w(email), [])
    |> validate_length(:email, min: 1, max: 20)
    |> unique_constraint(:email)
  end

  def registration_changeset(model, params) do
    model
    |> changeset(params)
    |> cast(params, ~w(password), [])
    |> validate_length(:password, min: 6, max: 100)
    |> put_pass_hash()
  end

  defp put_pass_hash(change) do
    case changes do
      %Ecto.Changeset{valid?: true, changes: %{password: pass}} ->
        put_change(change, :password_hash, Comeonin.Bcrypt.hashpwsalt(pass))
      _ ->
        change
    end
  end
end

web/controllers/admin/post_controller.ex
defmodule Blog.Admin.PostController do
  use Blog.Web, :controller
  alias Blog.Post

  plug :scrub_params, "post" when action in [:create, :update]
  plug Addict.Plugs.Authenticated when action in [:index]


  def index(conn, _params) do
    posts = Repo.paginate(Post, _params)

    render(conn, "index.html", posts: posts)
  end

  def new(conn, _params) do
    changeset = Post.changeset(%Post{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"post" => post_params}) do
    changeset = Post.changeset(%Post{}, post_params)

    case Repo.insert(changeset) do
      {:ok, _post} ->
        conn
        |> put_flash(:info, "Post created successfully.")
        |> redirect(to: admin_post_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    post = Repo.get!(Post, id)
    render(conn, "show.html", post: post)
  end

  def edit(conn, %{"id" => id}) do
    post = Repo.get!(Post, id)
    changeset = Post.changeset(post)
    render(conn, "edit.html", post: post, changeset: changeset)
  end

  def update(conn, %{"id" => id, "post" => post_params}) do
    post = Repo.get!(Post, id)
    changeset = Post.changeset(post, post_params)

    case Repo.update(changeset) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post updated successfully.")
        |> redirect(to: admin_post_path(conn, :show, post))
      {:error, changeset} ->
        render(conn, "edit.html", post: post, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    post = Repo.get!(Post, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(post)

    conn
    |> put_flash(:info, "Post deleted successfully.")
    |> redirect(to: admin_post_path(conn, :index))
  end
end

web/controllers/admin/user_controller.ex
defmodule Blog.Admin.UserController do
  use Blog.Web, :controller

  alias Blog.User

  plug :scrub_params, "user" when action in [:create, :update]

  def index(conn, _params) do
    users = Repo.paginate(User, _params)
    render(conn, "index.html", users: users)
  end

end

web/controllers/page_controller.ex
defmodule Blog.PageController do
  use Blog.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/post_controller.ex
defmodule Blog.PostController do
  use Blog.Web, :controller

  alias Blog.Post

  def index(conn, _params) do
    posts = Repo.paginate(Post, _params)
    render(conn, "index.html", posts: posts)
  end

  def show(conn, %{"id" => id}) do
    post = Repo.get!(Post, id)
    render(conn, "show.html", post: post)
  end
end

web/controllers/session_controller.ex
defmodule Blog.SessionController do
  use Blog.Web, :controller
  alias Blog.Auth

  def new(conn, _) do
    render conn, "new.html"
  end

  def create(conn, %{"session" => %{"email" => email, "password" => pass}}) do
    case Auth.login_by_username_and_pass(conn, email, pass, repo: Repo) do
      {:ok, conn} ->
        conn
        |> put_flash(:info, "Welcome back!")
        |> redirect(to: admin_post_path(conn, :index))
      {:error, _reason, conn} ->
        conn
        |> put_flash(:error, "Invalid username/password combination")
        |> render("new.html")
    end
  end

  def delete(conn, _) do
    conn
    |> Auth.logout()
    |> redirect(to: post_path(conn, :index))
  end
end

web/views/addict_view.ex
defmodule Addict.AddictView do
  use Phoenix.HTML
  use Phoenix.View, root: "web/templates/"
  import Phoenix.Controller, only: [view_module: 1]
  import Blog.Router.Helpers
end

web/views/admin/post_view.ex
defmodule Blog.Admin.PostView do
  use Blog.Web, :view
  alias Blog.Post
  import Scrivener.HTML
  import Phoenix.HTML.SimplifiedHelpers.Truncate

  def truncated_title(%Post{title: title}) do
    title
    |> truncate(length: 80)
  end
end

web/views/admin/user_view.ex
defmodule Blog.Admin.UserView do
  use Blog.Web, :view
  alias Blog.User
  import Scrivener.HTML
end

web/views/error_view.ex
defmodule Blog.ErrorView do
  use Blog.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Server internal error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule Blog.LayoutView do
  use Blog.Web, :view
end

web/views/page_view.ex
defmodule Blog.PageView do
  use Blog.Web, :view
end

web/views/post_view.ex
defmodule Blog.PostView do
  use Blog.Web, :view

  alias Blog.Post
  import Scrivener.HTML

end

web/views/session_view.ex
defmodule Blog.SessionView do
  use Blog.Web, :view
end

web/templates/addict/addict.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>User Management</title>
    <style type="text/css">
      /* Base styles */
      *, *:after, *:before {
        box-sizing: border-box;
      }
      html {
        font-size: 100%;
        line-height: 1.5;
        height: 100%;
      }

      body {
        position: relative;
        margin: 0;
        font-family: 'Work Sans', Arial, Helvetica, sans-serif;
        min-height: 100%;
        background: linear-gradient(to bottom, #A0A0A0 0%, #DEDEDE 100%);
        color: #777;
      }
      img {
        vertical-align: middle;
        max-width: 100%;
      }

      /* Container */
      .addict.container {
        position: absolute;
        width: 24em;
        left: 50%;
        top: 50%;
        transform: translate(-50%,-50%);
        animation: intro .7s cubic-bezier(0.175, 0.885, 0.32, 1.275) forwards;
      }

      /* Profile Card */
      /* Based on http://codepen.io/andrejmlinarevic/full/NGGdVv/ */
      .addict.modal {
        position: relative;
      }

      .addict.modal__form {
        visibility: visible;
        height: auto;
        opacity: 1;
        transform: translateY(-6em);
        padding-top: 12em;
      }
      .addict.modal__fields {
        opacity: 1;
      }
      .addict.modal__avatar {
        transform: translate(-50%, -1.5em);
        border-radius: 50%;
      }
      .addict.modal__form {
        position: relative;
        background: white;
        padding: 3em;
        border-radius: .25em;
        -webkit-filter: drop-shadow(0 0 2em rgba(0,0,0,0.2));
        transition:
          opacity .4s ease-in-out,
          height .4s ease-in-out,
          transform .4s cubic-bezier(0.175, 0.885, 0.32, 1.275),
          padding .4s cubic-bezier(0.175, 0.885, 0.32, 1.275);
      }

      .addict.modal__footer {
        padding-top: 1em;
      }


      /* Form */
      .addict.field {
        position: relative;
        margin-bottom: 2em;
      }
      .addict.label {
        position: absolute;
        height: 1.7rem;
        line-height: 2rem;
        bottom: 0;
        color: #999;
        transition: all .3s cubic-bezier(0.175, 0.885, 0.32, 1.275);
      }
      .addict.input {
        width: 100%;
        font-size: 100%;
        border: 0;
        padding: 0;
        background-color: transparent;
        height: 2rem;
        line-height: 2rem;
        border-bottom: 1px solid #eee;
        color: #777;
        transition: all .2s ease-in;
      }
      .addict.input:focus {
        outline: 0;
        border-color: #ccc;
      }

      /* Using required and a faux pattern to see if input has text from http://stackoverflow.com/questions/16952526/detect-if-an-input-has-text-in-it-using-css */
      .addict.input:focus + .label,
      .addict input:valid + .label {
        transform: translateY(-100%);
        font-size: 0.75rem;
        color: #ccc;
      }

      /* Button */
      .addict.btn {
        cursor: pointer;
        background-color: transparent;
        border: 0;
        font-size: 0.75rem;
        height: 2.5rem;
        line-height: 2.5rem;
        padding: 0 1.5rem;
        color: white;
        background: #999;
        text-transform: uppercase;
        border-radius: .25rem;
        letter-spacing: .2em;
        transition: background .2s;
      }
      .addict.btn:focus {
        outline: 0;
      }
      .addict.btn:hover,
      .addict.btn:focus {
        background: #000;
      }

      .addict a {
        text-decoration: none;
        color: #777;
        font-size: 80%;
      }

      .addict a:hover {
        color: #000;
        transition: color .2s;
      }

      .addict.error-message {
        margin-bottom: 0;
        margin-top: 0;
        color: #F00;
        font-size: 80%;
      }

      /* Intro animation */
      @keyframes intro {
        from {
          opacity: 0;
          top: 0;
        }
        to {
          opacity: 1;
          top: 50%;
        }
      }
    </style>
  </head>

  <body>
    <div class="container">
      <input type="hidden" id="csrf-token" value="<%= @csrf_token %>">

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script type="text/javascript">

      var btn_register = document.getElementById("btn-register");
      var btn_logout = document.getElementById("btn-logout");
      var btn_login = document.getElementById("btn-login");
      var btn_reset = document.getElementById("btn-reset-password");
      var btn_send = document.getElementById("btn-send-reset-password-link");

      function navigateToRoot() {
        window.location.href = "/";
      }

      function addErrors(errors) {
        var el = document.getElementsByClassName('errors')[0];

        function appendError(error_message, el) {
          var el_error = document.createElement("p");
          el_error.setAttribute("class", "addict error-message");
          el_error.innerText = error_message;
          el.appendChild(el_error);
        }

        if (errors) {
          errors = errors.errors;
          var i = errors.length - 1;
          errors.forEach(function(error) {
            appendError(error.message, el);
          });
        } else {
          appendError("Something went wrong, please try again", el);
        }
      }

      function clearErrors() {
        var el = document.getElementsByClassName('errors')[0];
        el.childNodes.length > 0 && Array.prototype.slice.call(el.childNodes).forEach(function(node){
          el.removeChild(node);
        });
      }

      function makeRequest(url, data, csrf_token, success_callback, failure_callback, method) {
        clearErrors();
        method = method || "POST";
        var xmlHttp = new XMLHttpRequest();
        xmlHttp.open(method, url);
        xmlHttp.setRequestHeader("x-csrf-token", csrf_token);
        xmlHttp.setRequestHeader("Content-Type", "application/json;charset=UTF-8");
        xmlHttp.onreadystatechange = function() {
          if (xmlHttp.readyState == 4) {
            if (xmlHttp.status >= 200 && xmlHttp.status < 400) {
              success_callback && success_callback();
            } else if (xmlHttp.status >= 400 && xmlHttp.status < 500){
              failure_callback && failure_callback(JSON.parse(xmlHttp.responseText));
            } else {
              failure_callback && failure_callback(null);
            }
          }
        }
        xmlHttp.send(JSON.stringify(data));
      }

      if(btn_register){
        document.getElementById("btn-register").addEventListener("click", function(ev) {
          var name = document.getElementById('txt-name').value;
          var email = document.getElementById('txt-email').value;
          var password = document.getElementById('txt-password').value;
          var csrf_token = document.getElementById('csrf-token').value;
          var params = {
            name: name,
            email: email,
            password: password
          };
          makeRequest('/register', params, csrf_token, navigateToRoot, addErrors);
        }, false);
      }

      if(btn_logout){
        document.getElementById("btn-logout").addEventListener("click", function(ev) {
          var csrf_token = document.getElementById('csrf-token').value;
          makeRequest('/logout', {}, csrf_token, navigateToRoot, null, "DELETE");
        }, false);
      }

      if(btn_login){
        document.getElementById("btn-login").addEventListener("click", function(ev) {
          var email = document.getElementById('txt-email').value;
          var password = document.getElementById('txt-password').value;
          var csrf_token = document.getElementById('csrf-token').value;
          var params = {
            email: email,
            password: password
          };
          makeRequest('/login', params, csrf_token, navigateToRoot, addErrors);
        }, false);
      }

      if(btn_reset){
        document.getElementById("btn-reset-password").addEventListener("click", function(ev) {
          var password = document.getElementById('txt-password').value;
          var token = document.getElementById('token').value;
          var signature = document.getElementById('signature').value;
          var csrf_token = document.getElementById('csrf-token').value;

          var params = {
            signature: signature,
            token: token,
            password: password
          };
          makeRequest('/reset_password', params, csrf_token, navigateToRoot, addErrors);
        }, false);
      }

      if(btn_send){
        document.getElementById("btn-send-reset-password-link").addEventListener("click", function(ev) {
          var email = document.getElementById('txt-email').value;
          var csrf_token = document.getElementById('csrf-token').value;

          var params = { email: email };
          makeRequest('/recover_password', params, csrf_token, navigateToRoot, addErrors);
        }, false);
      }

    </script>
  </body>
</html>

web/templates/addict/login.html.eex
<h1 style="text-align: center">Login</h1>
<div class="addict container">
  <div class="addict modal">
    <div class="addict modal__form">
      <div class="addict modal__fields">
        <div class="addict field">
          <input type="text" id="txt-email" class="addict input" required />
          <label for="txt-email" class="addict label">E-mail</label>
        </div>
        <div class="addict field">
          <input type="password" id="txt-password" class="addict input" required />
          <label for="txt-password" class="addict label">Password</label>
        </div>
        <div class="addict errors"></div>
        <div class="addict modal__footer">
          <button id="btn-login" class="addict btn">Login</button>
        </div>
        <a class="addict link" href="/recover_password">Forgot your password?</a>
      </div>
     </div>
  </div>
</div>

web/templates/addict/recover_password.html.eex
<h1 style="text-align: center">Recover Password</h1>
<div class="addict container">
  <div class="addict modal">
    <div class="addict modal__form">
      <div class="addict modal__fields">
        <div class="addict field">
          <input type="text" id="txt-email" class="addict input" required />
          <label for="txt-email" class="addict label">E-mail</label>
        </div>
        <div class="addict errors"></div>
        <div class="addict modal__footer">
          <button id="btn-send-reset-password-link" class="addict btn">Recover Password</button>
        </div>
      </div>
     </div>
  </div>
</div>

web/templates/addict/register.html.eex
<h1 style="text-align: center">Register</h1>
<div class="addict container">
  <div class="addict modal">
    <div class="addict modal__form">
      <div class="addict modal__fields">
        <div class="addict field">
          <input type="text" id="txt-name" class="addict input" required />
          <label for="txt-name" class="addict label">Name</label>
        </div>
        <div class="addict field">
          <input type="text" id="txt-email" class="addict input" required />
          <label for="txt-email" class="addict label">E-mail</label>
        </div>
        <div class="addict field">
          <input type="password" id="txt-password" class="addict input" required />
          <label for="txt-password" class="addict label">Password</label>
        </div>
        <div class="addict errors"></div>
        <div class="addict modal__footer">
          <button id="btn-register" class="addict btn">Register</button>
        </div>
      </div>
     </div>
  </div>
</div>

web/templates/addict/reset_password.html.eex
<h1 style="text-align: center">Reset Password</h1>
<div class="addict container">
  <div class="addict modal">
    <div class="addict modal__form">
      <div class="addict modal__fields">
        <div class="addict field">
          <input type="password" id="txt-password" class="addict input" required />
          <label for="txt-password" class="addict label">Password</label>
        </div>
        <div class="addict errors"></div>
        <div class="addict modal__footer">
          <button id="btn-reset-password" class="addict btn">Reset Password</button>
        </div>
      </div>
     </div>
  </div>
</div>

<input type="hidden" id="csrf-token" value="<%= @csrf_token %>">
<input type="hidden" id="token" value="<%= @token %>">
<input type="hidden" id="signature" value="<%= @signature %>">

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Hello Blog!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="container">
      <header class="header">
       <ol class="breadcrumb text-right">
          <%= if @current_user do %>
            <li><%= @current_user.email %></li>
            <li>
              <%= link "Log out", to: session_path(@conn, :delete, @current_user),
                                  method: "delete" %>
            </li>
          <% else %>
            <li><%= link "Log in", to: session_path(@conn, :new) %></li>
          <% end %>
        </ol>
      </header>

      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

web/templates/page/index.html.eex
<div class="jumbotron">
  <h2><%= gettext "Welcome to %{name}", name: "Phoenix!" %></h2>
  <p class="lead">A productive web framework that<br />does not compromise speed and maintainability.</p>
</div>

<div class="row marketing">
  <div class="col-lg-6">
    <h4>Resources</h4>
    <ul>
      <li>
        <a href="http://phoenixframework.org/docs/overview">Guides</a>
      </li>
      <li>
        <a href="http://hexdocs.pm/phoenix">Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
    </ul>
  </div>

  <div class="col-lg-6">
    <h4>Help</h4>
    <ul>
      <li>
        <a href="http://groups.google.com/group/phoenix-talk">Mailing list</a>
      </li>
      <li>
        <a href="http://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">@elixirphoenix</a>
      </li>
    </ul>
  </div>
</div>

web/templates/post/index.html.eex
<%= for post <- @posts do %>

  <h2>
    <%= link post.title, to: post_path(@conn, :show, post) %>
  </h2>
  <p>
    <%= post.content %>
  </p>

<% end %>

<%= pagination_links @conn, @posts, path: &post_path/3 %>

web/templates/post/show.html.eex
<h1> <%= @post.title %> </h1>

<p>
  <%= @post.content %>
</p>

web/templates/session/new.html.eex
<h1>Login</h1>

<%= form_for @conn, session_path(@conn, :create), [as: :session], fn f -> %>
  <div class="form-group">
    <%= text_input f, :email, placeholder: "Email", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= password_input f, :password, placeholder: "Password", class: "form-control" %>
  </div>
  <%= submit "Log in", class: "btn btn-primary" %>
<% end %>